name: "Lunda – Forgotten Branch Scanner"
description: "Detect and list forgotten branches in your repository"
author: "Merlin & One very famous neural network"
branding:
  color: "blue"
  icon: "eye"

inputs:
  days_threshold:
    description: "Number of days of inactivity before a branch is considered forgotten"
    required: false
    default: 90

runs:
  using: "node16"
  main: "code/scripts/checkBranches.js"
